# version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    volumes:
      - .web:/var/www/html
    networks:
      - inception_network
  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    env_file: .env
    volumes:
      - .web:/var/www/html
    networks:
      - inception_network
  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    networks:
      - inception_network

networks:
    inception_network:
      driver: bridge